packages:
  - 'apis/*'
  - 'apps/*'
  - 'config/*'
  - 'packages/**'
  - 'protocols/*'
  - 'config/*'
  - 'packages/**'
  - 'protocols/*'  - 'config/*'
  - 'packages/**'
  - 'protocols/*'  - 'config/*'
  - 'packages/**'
  - 'protocols/*'  - 'config/*'
  - 'packages/**'
  - 'protocols/*'  - 'config/*'
  - 'packages/**'
  - 'protocols/*'
